# Base configs
baseurl: "/speed-of-light"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
#google_analytics: "UA-55626306-1"

# UI configs
title: "Speed of Light"
subtitle: "Travels through space and time"
author: "Darko"
header: 
 title: "Speed of Light"
 subtitle: ""
footer:
 bio: "Shooting for the love of photography, as a meditative waltz through nature or urban scenes and other curiosities, as a way of seeing through the blinkers that day to day living sometimes covers our eyes with, to the transcendent beauty hidden in the humdrum."
 publicise: "All images Copyright Chandra Sivaraman, 2016-2050"
web_design: "AJ"
social_urls:
  instagram: "https://www.instagram.com/cs31415/"